/**
 * KOReader stores its settings as Lua files that `return` a table, loaded with
 * loadfile. If the file is not valid Lua, KOReader silently discards it and the
 * user is back to typing everything, so the serialization here has to be
 * exactly right: every string escaped, the whole thing a single returned table.
 *
 * These generators produce the two files that make an e-reader "just work":
 * the OPDS catalog (the user's library) and the kosync config (position sync).
 */

/**
 * Escape a string for a Lua double-quoted literal. Covers the characters that
 * would otherwise break the file or change its meaning.
 */
function luaString(value: string): string {
  const escaped = value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n")
    .replaceAll("\r", "\\r")
    .replaceAll("\t", "\\t")
  return `"${escaped}"`
}

export type OpdsCatalog = {
  title: string
  url: string
  username: string
  password: string
}

/**
 * KOReader reads OPDS catalogs from settings/opds.lua. The `servers` array is
 * the list of catalogs; each carries its own basic-auth credentials.
 */
export function generateOpdsLua(catalogs: OpdsCatalog[]): string {
  const servers = catalogs
    .map(
      (catalog) =>
        `        {
            ["title"] = ${luaString(catalog.title)},
            ["url"] = ${luaString(catalog.url)},
            ["username"] = ${luaString(catalog.username)},
            ["password"] = ${luaString(catalog.password)},
        },`,
    )
    .join("\n")

  return `-- Generated by Storyteller. Sets up your library so you never have to
-- type a server address or password on your e-reader.
return {
    ["servers"] = {
${servers}
    },
}
`
}

export type KosyncConfig = {
  customServer: string
  username: string
  /** md5-style hex digest KOReader sends as the auth key; never a plaintext password. */
  userkey: string
}

/**
 * KOReader's kosync plugin reads settings/kosync.lua. Seeding `username` and
 * `userkey` logs the device in without the user typing anything. `auto_sync`
 * makes position sync happen on its own; `checksum_method = 0` is the binary
 * (partial-md5) document match, which is what lets the same book line up across
 * devices and against Storyteller's own hashing.
 */
export function generateKosyncLua(config: KosyncConfig): string {
  return `-- Generated by Storyteller. Logs this device in to reading-position sync
-- so your place follows you between your e-reader and the Storyteller apps.
return {
    ["settings"] = {
        ["custom_server"] = ${luaString(config.customServer)},
        ["username"] = ${luaString(config.username)},
        ["userkey"] = ${luaString(config.userkey)},
        ["auto_sync"] = true,
        ["checksum_method"] = 0,
    },
}
`
}
